name: Publish Helm Chart to GHCR

on:
  workflow_call:
    inputs:
      chart-path:
        description: "Path to the chart directory (e.g. base-chart)"
        required: true
        type: string
      ghcr-org:
        description: "GitHub org or username (used in ghcr.io/<org>/<chart>)"
        required: true
        type: string
      chart-name:
        description: "The name to use for the chart in GHCR"
        required: true
        type: string
    secrets:
      GHCR_USERNAME:
        required: true
      GHCR_TOKEN:
        required: true

permissions:
  contents: write

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # -----------------------------
      # Versioning step
      # -----------------------------
      - name: Determine new version
        uses: besqpin/workflow-library/.github/workflows/versioning.yaml@main
        id: versioning
        with:
          event_name: ${{ github.event_name }}
          pr_merged: ${{ github.event.pull_request.merged }}

      - name: Update Chart.yaml in runner
        run: |
          NEW_VERSION="${{ steps.versioning.outputs.new_tag }}"
          echo "Updating Chart.yaml with version $NEW_VERSION (runner only)"

          # Update 'version' and 'appVersion' in place
          yq eval ".version = \"${NEW_VERSION#v}\"" -i ${{ inputs.chart-path }}/Chart.yaml
          yq eval ".appVersion = \"${NEW_VERSION#v}\"" -i ${{ inputs.chart-path }}/Chart.yaml

      # -----------------------------
      # Helm packaging and publish
      # -----------------------------
      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Package Helm chart
        run: |
          NEW_VERSION="${{ steps.versioning.outputs.new_tag }}"
          helm package ${{ inputs.chart-path }} \
            --version "${NEW_VERSION#v}" \
            --app-version "${NEW_VERSION#v}"

      - name: Log in to GHCR
        run: |
          echo "${{ secrets.GHCR_TOKEN }}" | helm registry login ghcr.io \
            -u ${{ secrets.GHCR_USERNAME }} --password-stdin

      - name: Push Helm chart to GHCR
        run: |
          FILE=$(ls *.tgz | head -n1)
          if [ -z "$FILE" ]; then
            echo "Error: No packaged chart found!"
            exit 1
          fi
          echo "Pushing $FILE to ghcr.io/${{ inputs.ghcr-org }}/${{ inputs.chart-name }}..."
          helm push $FILE oci://ghcr.io/${{ inputs.ghcr-org }}/${{ inputs.chart-name }}
