name: Publish Helm Chart

on:
  workflow_call:
    inputs:
      chart-path:
        description: "Path to the chart directory (e.g. base-chart)"
        required: true
        type: string
      docker-org:
        description: "Docker Hub org/user name"
        required: true
        type: string
    secrets:
      DOCKER_USERNAME:
        required: true
      DOCKER_TOKEN:
        required: true

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: v3.14.4

      - name: Extract version from Chart.yaml
        id: chart_version
        run: |
          VERSION=$(yq e '.version' ${{ inputs.chart-path }}/Chart.yaml)
          APP_VERSION=$(yq e '.appVersion' ${{ inputs.chart-path }}/Chart.yaml)
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT

      - name: Package Helm chart
        run: |
          helm package ${{ inputs.chart-path }} \
            --version ${{ steps.chart_version.outputs.version }} \
            --app-version ${{ steps.chart_version.outputs.app_version }}

      - name: Log in to Docker Hub (Helm)
        run: |
          echo "${{ secrets.DOCKER_TOKEN }}" | helm registry login registry-1.docker.io \
            -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Push Helm chart to Docker Hub
        run: |
          FILE=$(ls *.tgz | head -n1)
          if [ -z "$FILE" ]; then
            echo "Error: No packaged chart found!"
            exit 1
          fi
          echo "Pushing $FILE to Docker Hub..."
          helm push $FILE oci://registry-1.docker.io/${{ inputs.docker-org }}
